version: '3.8'

services:
  mongo:
    image: mongo:6.0
    environment:
      - MONGO_URL=mongodb://mongo:27017/dev
    volumes:
      - mongo_db_ddd:/data/db
      # - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=codely
      - POSTGRES_USER=codely
      - POSTGRES_DB=mooc-backend-dev
    ports:
      - '5432:5432'
    restart: always
    user: postgres
    volumes:
      - postgres_db_ddd:/var/lib/postgresql/data

volumes:
  postgres_db_ddd:
  mongo_db_ddd:
